version: '3.5'

services:
  # Services.
  heimdallr:
    container_name: heimdallr
    image: yggdrasil/heimdallr
    build:
      context: images/node14.15.1-alpine
    volumes:
      - ../heimdallr:/usr/app:delegated
    env_file:
      - .config/heimdallr/.env
    working_dir: /usr/app
    networks:
      - yggdrasil
      - midgard
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - valhalla
      - valkyrie

  valkyrie:
    container_name: valkyrie
    image: yggdrasil/valkyrie
    build:
      context: images/node14.15.1-alpine
    volumes:
      - ../valkyrie:/usr/app:delegated
    env_file:
      - .config/valkyrie/.env
    working_dir: /usr/app
    networks:
      - yggdrasil
    ports:
    - "3000:3000"
    command: yarn start
    depends_on:
      - valhalla

  # Databases.
  valhalla:
    container_name: valhalla
    image: yggdrasil/valhalla
    build:
      context: images/postgres12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    networks:
      - yggdrasil
      - midgard
    ports:
      - "5432:5432"

networks:
  yggdrasil:
    internal: true
    name: yggdrasil
  midgard:
    name: midgard
