version: '3.5'

services:
  dependencies:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: dependencies
    container_name: dependencies
    image: yggdrasil/dependencies
    networks:
      - yggdrasil
    volumes:
      - ./node_mdules:/node_modules:delegated

  # Applications
  heimdallr:
    build:
      args:
        app_name: heimdallr
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: heimdallr
    entrypoint: "yarn start:heimdallr"
    image: yggdrasil/heimdallr
    networks:
      - yggdrasil
      - midgard
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:delegated
      - ./apps/heimdallr:/usr/app/apps/heimdallr:delegated
      - ./libs:/usr/app/libs:delegated

  valhalla:
    build:
      args:
        app_name: valhalla
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: valhalla
    depends_on:
      - dependencies
    entrypoint: "yarn start:valhalla"
    image: yggdrasil/valhalla
    networks:
      - yggdrasil
      - midgard
    ports:
      - "3001:3001"
    volumes:
      - ./node_modules:/usr/app/node_modules:delegated
      - ./apps/valhalla:/usr/app/apps/valhalla:delegated
      - ./libs:/usr/app/libs:delegated

  # Databases.
#  valhalla:
#    container_name: valhalla
#    image: yggdrasil/valhalla
#    build:
#      context: images/postgres12-alpine
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: admin
#    networks:
#      - yggdrasil
#      - midgard
#    ports:
#      - "5432:5432"

networks:
  yggdrasil:
    internal: true
    name: yggdrasil
  midgard:
    name: midgard
