version: '3.5'

services:
  # Applications
  heimdallr:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: heimdallr
    depends_on:
      - mimir
      - valhalla
    entrypoint: "yarn start:watch"
    env_file:
      - apps/heimdallr/.env.dev
    image: yggdrasil/heimdallr
    networks:
      - yggdrasil
      - midgard
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/heimdallr:/usr/app/apps/heimdallr:cached
      - ./libs:/usr/app/libs:cached

  mimir:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: mimir
    depends_on:
      - db
      - mimisbrunnr
    entrypoint: "yarn start:watch"
    env_file:
      - apps/mimir/.env.dev
    image: yggdrasil/mimir
    networks:
      - yggdrasil
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/mimir:/usr/app/apps/mimir:cached
      - ./libs:/usr/app/libs:cached

  valhalla:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: valhalla
    depends_on:
      - db
    entrypoint: "yarn start:watch"
    env_file:
      - apps/valhalla/.env.dev
    image: yggdrasil/valhalla
    networks:
      - yggdrasil
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/valhalla:/usr/app/apps/valhalla:cached
      - ./libs:/usr/app/libs:cached

  # Databases
  db:
    build:
      context: images/postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    image: yggdrasil/db
    networks:
      - yggdrasil
      - midgard
    ports:
      - "5432:5432"

  mimisbrunnr:
    container_name: mimisbrunnr
    build:
      context: images/redis
    image: yggdrasil/mimisbrunnr
    networks:
      - yggdrasil
      - midgard
    ports:
      - "6379:6379"

networks:
  yggdrasil:
    internal: true
    name: yggdrasil
  midgard:
    name: midgard
