version: '3.5'

services:
  # Applications
  heimdallr:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: heimdallr
    depends_on:
      - mimir
      - valhalla
    entrypoint: "yarn start:watch"
    env_file:
      - apps/heimdallr/.env.dev
    image: yggdrasil/heimdallr
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/heimdallr:/usr/app/apps/heimdallr:cached
      - ./libs:/usr/app/libs:cached

  midgard:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: midgard
    entrypoint: "yarn start:watch"
    env_file:
      - apps/midgard/.env.dev
    image: yggdrasil/midgard
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "8080:8080"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/midgard:/usr/app/apps/midgard:cached
      - ./libs:/usr/app/libs:cached

  mimir:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: mimir
    depends_on:
      - mongodb
      - redis
    entrypoint: "yarn start:watch"
    env_file:
      - apps/mimir/.env.dev
    image: yggdrasil/mimir
    networks:
      - yggdrasil
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/mimir:/usr/app/apps/mimir:cached
      - ./libs:/usr/app/libs:cached

  nidavellir:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: nidavellir
    depends_on:
      - mongodb
    entrypoint: "yarn start:watch"
    env_file:
      - apps/nidavellir/.env.dev
    image: yggdrasil/nidavellir
    networks:
      - yggdrasil
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/nidavellir:/usr/app/apps/nidavellir:cached
      - ./libs:/usr/app/libs:cached

  valhalla:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: valhalla
    depends_on:
      - mongodb
    entrypoint: "yarn start:watch"
    env_file:
      - apps/valhalla/.env.dev
    image: yggdrasil/valhalla
    networks:
      - yggdrasil
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/valhalla:/usr/app/apps/valhalla:cached
      - ./libs:/usr/app/libs:cached

  # Databases
  mongodb:
    build:
      context: images/mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    image: yggdrasil/mongodb
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "27017:27017"

  redis:
    build:
      context: images/redis
    container_name: redis
    image: yggdrasil/redis
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "6379:6379"

networks:
  yggdrasil:
    internal: true
    name: yggdrasil
  bifrost:
    name: bifrost
