version: '3.5'

services:
  heimdallr_test:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: heimdallr_test
    depends_on:
      - mimir_test
      - valhalla_test
    entrypoint: "yarn start"
    env_file:
      - apps/heimdallr/.env.test
    image: yggdrasil/heimdallr_test
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000/health" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - yggdrasil_test
      - bifrost_test
    ports:
      - "${EXTERNAL_APP_PORT:-3001}:3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/heimdallr:/usr/app/apps/heimdallr:cached
      - ./libs:/usr/app/libs:cached

  mimir_test:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: mimir_test
    depends_on:
      - mongodb_test
      - redis_test
    entrypoint: "yarn start"
    env_file:
      - apps/mimir/.env.test
    image: yggdrasil/mimir_test
    networks:
      - yggdrasil_test
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/mimir:/usr/app/apps/mimir:cached
      - ./libs:/usr/app/libs:cached

  valhalla_test:
    build:
      context: .
      dockerfile: images/node/Dockerfile
      target: application
    container_name: valhalla_test
    depends_on:
      - mongodb_test
    entrypoint: "yarn start"
    env_file:
      - apps/valhalla/.env.test
    image: yggdrasil/valhalla_test
    networks:
      - yggdrasil_test
    ports:
      - "3000"
    volumes:
      - ./node_modules:/usr/app/node_modules:cached
      - ./apps/valhalla:/usr/app/apps/valhalla:cached
      - ./libs:/usr/app/libs:cached

  mongodb_test:
    build:
      context: images/mongo
    container_name: mongodb_test
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${EXTERNAL_MONGO_PASSWORD:-password}
      MONGO_INITDB_ROOT_USERNAME: ${EXTERNAL_MONGO_USER:-admin}
    image: yggdrasil/mongodb_test
    networks:
      - yggdrasil_test
      - bifrost_test
    ports:
      - "${EXTERNAL_MONGO_PORT:-27018}:27017"

  redis_test:
    container_name: redis_test
    build:
      context: images/redis
    image: yggdrasil/redis_test
    networks:
      - yggdrasil_test
      - bifrost_test
    ports:
      - "6379"

networks:
  yggdrasil_test:
    internal: true
    name: yggdrasil_test
  bifrost_test:
    name: bifrost_test
