version: '3.5'

services:
  # Services.
  heimdallr:
    container_name: heimdallr
    image: yggdrasil/heimdallr
    build:
      context: images/node14.15.1-alpine
    volumes:
      - ../heimdallr:/usr/app:delegated
    env_file:
      - .config/heimdallr/.env
    working_dir: /usr/app
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - valhalla
      - mimir
      - valkyrie

  mimir:
    container_name: mimir
    image: yggdrasil/mimir
    build:
      context: images/golang1.14.2-alpine
    volumes:
      - ../mimir:/usr/app:delegated
    env_file:
      - .config/mimir/.env
    working_dir: /usr/app
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh", "./scripts/start.sh"]
    depends_on:
      - mimisbrunnr
      - valhalla

  valkyrie:
    container_name: valkyrie
    image: yggdrasil/valkyrie
    build:
      context: images/node14.15.1-alpine
    volumes:
      - ../valkyrie:/usr/app:delegated
    env_file:
      - .config/valkyrie/.env
    working_dir: /usr/app
    networks:
      - yggdrasil
    ports:
    - "3000:3000"
    command: yarn start
    depends_on:
      - valhalla

  # Databases.
  valhalla:
    container_name: valhalla
    image: yggdrasil/valhalla
    build:
      context: images/postgres12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "5432:5432"

  mimisbrunnr:
    container_name: mimisbrunnr
    image: yggdrasil/mimisbrunnr
    build:
      context: images/redis6.0.9-alpine
    networks:
      - yggdrasil
      - bifrost
    ports:
      - "6379:6379"

networks:
  yggdrasil:
    internal: true
    name: yggdrasil
  bifrost:
    name: bifrost
